/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters.
 */
export interface ActivityTotal { 
    /**
     * The number of activities considered in this total.
     */
    count?: number;
    /**
     * The total distance covered by the considered activities.
     */
    distance?: number;
    /**
     * The total moving time of the considered activities.
     */
    moving_time?: number;
    /**
     * The total elapsed time of the considered activities.
     */
    elapsed_time?: number;
    /**
     * The total elevation gain of the considered activities.
     */
    elevation_gain?: number;
    /**
     * The total number of achievements of the considered activities.
     */
    achievement_count?: number;
}

