/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityTotal } from './activityTotal.interface';


/**
 * A set of rolled-up statistics and totals for an athlete
 */
export interface ActivityStats { 
    /**
     * The longest distance ridden by the athlete.
     */
    biggest_ride_distance?: number;
    /**
     * The highest climb ridden by the athlete.
     */
    biggest_climb_elevation_gain?: number;
    recent_ride_totals?: ActivityTotal;
    recent_run_totals?: ActivityTotal;
    recent_swim_totals?: ActivityTotal;
    ytd_ride_totals?: ActivityTotal;
    ytd_run_totals?: ActivityTotal;
    ytd_swim_totals?: ActivityTotal;
    all_ride_totals?: ActivityTotal;
    all_run_totals?: ActivityTotal;
    all_swim_totals?: ActivityTotal;
}

