/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimedZoneRange } from './timedZoneRange.interface';


export interface ActivityZone { 
    score?: number;
    /**
     * Stores the exclusive ranges representing zones and the time spent in each.
     */
    distribution_buckets?: TimedZoneRange[];
    type?: ActivityZone.TypeEnum;
    sensor_based?: boolean;
    points?: number;
    custom_zones?: boolean;
    max?: number;
}
export namespace ActivityZone {
    export type TypeEnum = 'heartrate' | 'power';
    export const TypeEnum = {
        heartrate: 'heartrate' as TypeEnum,
        power: 'power' as TypeEnum
    };
}


