/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration of the types an activity may have. Note that this enumeration does not include new sport types (e.g. MountainBikeRide, EMountainBikeRide), activities with these sport types will have the corresponding activity type (e.g. Ride for MountainBikeRide, EBikeRide for EMountainBikeRide)
 */
export type ActivityType = 'AlpineSki' | 'BackcountrySki' | 'Canoeing' | 'Crossfit' | 'EBikeRide' | 'Elliptical' | 'Golf' | 'Handcycle' | 'Hike' | 'IceSkate' | 'InlineSkate' | 'Kayaking' | 'Kitesurf' | 'NordicSki' | 'Ride' | 'RockClimbing' | 'RollerSki' | 'Rowing' | 'Run' | 'Sail' | 'Skateboard' | 'Snowboard' | 'Snowshoe' | 'Soccer' | 'StairStepper' | 'StandUpPaddling' | 'Surfing' | 'Swim' | 'Velomobile' | 'VirtualRide' | 'VirtualRun' | 'Walk' | 'WeightTraining' | 'Wheelchair' | 'Windsurf' | 'Workout' | 'Yoga';

export const ActivityType = {
    alpineSki: 'AlpineSki' as ActivityType,
    backcountrySki: 'BackcountrySki' as ActivityType,
    canoeing: 'Canoeing' as ActivityType,
    crossfit: 'Crossfit' as ActivityType,
    eBikeRide: 'EBikeRide' as ActivityType,
    elliptical: 'Elliptical' as ActivityType,
    golf: 'Golf' as ActivityType,
    handcycle: 'Handcycle' as ActivityType,
    hike: 'Hike' as ActivityType,
    iceSkate: 'IceSkate' as ActivityType,
    inlineSkate: 'InlineSkate' as ActivityType,
    kayaking: 'Kayaking' as ActivityType,
    kitesurf: 'Kitesurf' as ActivityType,
    nordicSki: 'NordicSki' as ActivityType,
    ride: 'Ride' as ActivityType,
    rockClimbing: 'RockClimbing' as ActivityType,
    rollerSki: 'RollerSki' as ActivityType,
    rowing: 'Rowing' as ActivityType,
    run: 'Run' as ActivityType,
    sail: 'Sail' as ActivityType,
    skateboard: 'Skateboard' as ActivityType,
    snowboard: 'Snowboard' as ActivityType,
    snowshoe: 'Snowshoe' as ActivityType,
    soccer: 'Soccer' as ActivityType,
    stairStepper: 'StairStepper' as ActivityType,
    standUpPaddling: 'StandUpPaddling' as ActivityType,
    surfing: 'Surfing' as ActivityType,
    swim: 'Swim' as ActivityType,
    velomobile: 'Velomobile' as ActivityType,
    virtualRide: 'VirtualRide' as ActivityType,
    virtualRun: 'VirtualRun' as ActivityType,
    walk: 'Walk' as ActivityType,
    weightTraining: 'WeightTraining' as ActivityType,
    wheelchair: 'Wheelchair' as ActivityType,
    windsurf: 'Windsurf' as ActivityType,
    workout: 'Workout' as ActivityType,
    yoga: 'Yoga' as ActivityType
};

