/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryAthlete } from './summaryAthlete.interface';


export interface Comment { 
    /**
     * The unique identifier of this comment
     */
    id?: number;
    /**
     * The identifier of the activity this comment is related to
     */
    activity_id?: number;
    /**
     * The content of the comment
     */
    text?: string;
    athlete?: SummaryAthlete;
    /**
     * The time at which this comment was created.
     */
    created_at?: string;
}

