/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExplorerSegment } from './explorerSegment.interface';


export interface ExplorerResponse { 
    /**
     * The set of segments matching an explorer request
     */
    segments?: ExplorerSegment[];
}

