/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExplorerSegment { 
    /**
     * The unique identifier of this segment
     */
    id?: number;
    /**
     * The name of this segment
     */
    name?: string;
    /**
     * The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. If climb_category = 5, climb_category_desc = HC. If climb_category = 2, climb_category_desc = 3.
     */
    climb_category?: number;
    /**
     * The description for the category of the climb
     */
    climb_category_desc?: ExplorerSegment.ClimbCategoryDescEnum;
    /**
     * The segment\'s average grade, in percents
     */
    avg_grade?: number;
    /**
     * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
     */
    start_latlng?: number[];
    /**
     * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
     */
    end_latlng?: number[];
    /**
     * The segments\'s evelation difference, in meters
     */
    elev_difference?: number;
    /**
     * The segment\'s distance, in meters
     */
    distance?: number;
    /**
     * The polyline of the segment
     */
    points?: string;
}
export namespace ExplorerSegment {
    export type ClimbCategoryDescEnum = 'NC' | '4' | '3' | '2' | '1' | 'HC';
    export const ClimbCategoryDescEnum = {
        nc: 'NC' as ClimbCategoryDescEnum,
        _4: '4' as ClimbCategoryDescEnum,
        _3: '3' as ClimbCategoryDescEnum,
        _2: '2' as ClimbCategoryDescEnum,
        _1: '1' as ClimbCategoryDescEnum,
        hc: 'HC' as ClimbCategoryDescEnum
    };
}


