/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Encapsulates the errors that may be returned from the API.
 */
export interface Fault { 
    /**
     * The set of specific errors associated with this fault, if any.
     */
    errors?: Error[];
    /**
     * The message of the fault.
     */
    message?: string;
}

