/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelError { 
    /**
     * The code associated with this error.
     */
    code?: string;
    /**
     * The specific field or aspect of the resource associated with this error.
     */
    field?: string;
    /**
     * The type of resource associated with this error.
     */
    resource?: string;
}

