/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotosSummaryPrimary } from './photosSummaryPrimary.interface';


export interface PhotosSummary { 
    /**
     * The number of photos
     */
    count?: number;
    primary?: PhotosSummaryPrimary;
}

