/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PhotosSummaryPrimary { 
    id?: number;
    source?: number;
    unique_id?: string;
    urls?: Record<string, string>;
}

