/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PolylineMap { 
    /**
     * The identifier of the map
     */
    id?: string;
    /**
     * The polyline of the map, only returned on detailed representation of an object
     */
    polyline?: string;
    /**
     * The summary polyline of the map
     */
    summary_polyline?: string;
}

