/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZoneRange } from './zoneRange.interface';


export interface PowerZoneRanges { 
    zones?: ZoneRange[];
}

