/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryAthlete } from './summaryAthlete.interface';
import { Waypoint } from './waypoint.interface';
import { PolylineMap } from './polylineMap.interface';
import { SummarySegment } from './summarySegment.interface';


export interface Route { 
    athlete?: SummaryAthlete;
    /**
     * The description of the route
     */
    description?: string;
    /**
     * The route\'s distance, in meters
     */
    distance?: number;
    /**
     * The route\'s elevation gain.
     */
    elevation_gain?: number;
    /**
     * The unique identifier of this route
     */
    id?: number;
    /**
     * The unique identifier of the route in string format
     */
    id_str?: string;
    map?: PolylineMap;
    /**
     * The name of this route
     */
    name?: string;
    /**
     * Whether this route is private
     */
    'private'?: boolean;
    /**
     * Whether this route is starred by the logged-in athlete
     */
    starred?: boolean;
    /**
     * An epoch timestamp of when the route was created
     */
    timestamp?: number;
    /**
     * This route\'s type (1 for ride, 2 for runs)
     */
    type?: number;
    /**
     * This route\'s sub-type (1 for road, 2 for mountain bike, 3 for cross, 4 for trail, 5 for mixed)
     */
    sub_type?: number;
    /**
     * The time at which the route was created
     */
    created_at?: string;
    /**
     * The time at which the route was last updated
     */
    updated_at?: string;
    /**
     * Estimated time in seconds for the authenticated athlete to complete route
     */
    estimated_moving_time?: number;
    /**
     * The segments traversed by this route
     */
    segments?: SummarySegment[];
    /**
     * The custom waypoints along this route
     */
    waypoints?: Waypoint[];
}

