/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
 */
export type SportType = 'AlpineSki' | 'BackcountrySki' | 'Badminton' | 'Canoeing' | 'Crossfit' | 'EBikeRide' | 'Elliptical' | 'EMountainBikeRide' | 'Golf' | 'GravelRide' | 'Handcycle' | 'HighIntensityIntervalTraining' | 'Hike' | 'IceSkate' | 'InlineSkate' | 'Kayaking' | 'Kitesurf' | 'MountainBikeRide' | 'NordicSki' | 'Pickleball' | 'Pilates' | 'Racquetball' | 'Ride' | 'RockClimbing' | 'RollerSki' | 'Rowing' | 'Run' | 'Sail' | 'Skateboard' | 'Snowboard' | 'Snowshoe' | 'Soccer' | 'Squash' | 'StairStepper' | 'StandUpPaddling' | 'Surfing' | 'Swim' | 'TableTennis' | 'Tennis' | 'TrailRun' | 'Velomobile' | 'VirtualRide' | 'VirtualRow' | 'VirtualRun' | 'Walk' | 'WeightTraining' | 'Wheelchair' | 'Windsurf' | 'Workout' | 'Yoga';

export const SportType = {
    alpineSki: 'AlpineSki' as SportType,
    backcountrySki: 'BackcountrySki' as SportType,
    badminton: 'Badminton' as SportType,
    canoeing: 'Canoeing' as SportType,
    crossfit: 'Crossfit' as SportType,
    eBikeRide: 'EBikeRide' as SportType,
    elliptical: 'Elliptical' as SportType,
    eMountainBikeRide: 'EMountainBikeRide' as SportType,
    golf: 'Golf' as SportType,
    gravelRide: 'GravelRide' as SportType,
    handcycle: 'Handcycle' as SportType,
    highIntensityIntervalTraining: 'HighIntensityIntervalTraining' as SportType,
    hike: 'Hike' as SportType,
    iceSkate: 'IceSkate' as SportType,
    inlineSkate: 'InlineSkate' as SportType,
    kayaking: 'Kayaking' as SportType,
    kitesurf: 'Kitesurf' as SportType,
    mountainBikeRide: 'MountainBikeRide' as SportType,
    nordicSki: 'NordicSki' as SportType,
    pickleball: 'Pickleball' as SportType,
    pilates: 'Pilates' as SportType,
    racquetball: 'Racquetball' as SportType,
    ride: 'Ride' as SportType,
    rockClimbing: 'RockClimbing' as SportType,
    rollerSki: 'RollerSki' as SportType,
    rowing: 'Rowing' as SportType,
    run: 'Run' as SportType,
    sail: 'Sail' as SportType,
    skateboard: 'Skateboard' as SportType,
    snowboard: 'Snowboard' as SportType,
    snowshoe: 'Snowshoe' as SportType,
    soccer: 'Soccer' as SportType,
    squash: 'Squash' as SportType,
    stairStepper: 'StairStepper' as SportType,
    standUpPaddling: 'StandUpPaddling' as SportType,
    surfing: 'Surfing' as SportType,
    swim: 'Swim' as SportType,
    tableTennis: 'TableTennis' as SportType,
    tennis: 'Tennis' as SportType,
    trailRun: 'TrailRun' as SportType,
    velomobile: 'Velomobile' as SportType,
    virtualRide: 'VirtualRide' as SportType,
    virtualRow: 'VirtualRow' as SportType,
    virtualRun: 'VirtualRun' as SportType,
    walk: 'Walk' as SportType,
    weightTraining: 'WeightTraining' as SportType,
    wheelchair: 'Wheelchair' as SportType,
    windsurf: 'Windsurf' as SportType,
    workout: 'Workout' as SportType,
    yoga: 'Yoga' as SportType
};

