/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistanceStream } from './distanceStream.interface';
import { SmoothGradeStream } from './smoothGradeStream.interface';
import { TemperatureStream } from './temperatureStream.interface';
import { PowerStream } from './powerStream.interface';
import { AltitudeStream } from './altitudeStream.interface';
import { CadenceStream } from './cadenceStream.interface';
import { HeartrateStream } from './heartrateStream.interface';
import { TimeStream } from './timeStream.interface';
import { SmoothVelocityStream } from './smoothVelocityStream.interface';
import { LatLngStream } from './latLngStream.interface';
import { MovingStream } from './movingStream.interface';


export interface StreamSet { 
    time?: TimeStream;
    distance?: DistanceStream;
    latlng?: LatLngStream;
    altitude?: AltitudeStream;
    velocity_smooth?: SmoothVelocityStream;
    heartrate?: HeartrateStream;
    cadence?: CadenceStream;
    watts?: PowerStream;
    temp?: TemperatureStream;
    moving?: MovingStream;
    grade_smooth?: SmoothGradeStream;
}

