/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SummaryAthlete { 
    /**
     * The unique identifier of the athlete
     */
    id?: number;
    /**
     * Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
     */
    resource_state?: number;
    /**
     * The athlete\'s first name.
     */
    firstname?: string;
    /**
     * The athlete\'s last name.
     */
    lastname?: string;
    /**
     * URL to a 62x62 pixel profile picture.
     */
    profile_medium?: string;
    /**
     * URL to a 124x124 pixel profile picture.
     */
    profile?: string;
    /**
     * The athlete\'s city.
     */
    city?: string;
    /**
     * The athlete\'s state or geographical region.
     */
    state?: string;
    /**
     * The athlete\'s country.
     */
    country?: string;
    /**
     * The athlete\'s sex.
     */
    sex?: SummaryAthlete.SexEnum;
    /**
     * Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
     */
    premium?: boolean;
    /**
     * Whether the athlete has any Summit subscription.
     */
    summit?: boolean;
    /**
     * The time at which the athlete was created.
     */
    created_at?: string;
    /**
     * The time at which the athlete was last updated.
     */
    updated_at?: string;
}
export namespace SummaryAthlete {
    export type SexEnum = 'M' | 'F';
    export const SexEnum = {
        m: 'M' as SexEnum,
        f: 'F' as SexEnum
    };
}


