/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SummarySegmentEffort { 
    /**
     * The unique identifier of this effort
     */
    id?: number;
    /**
     * The unique identifier of the activity related to this effort
     */
    activity_id?: number;
    /**
     * The effort\'s elapsed time
     */
    elapsed_time?: number;
    /**
     * The time at which the effort was started.
     */
    start_date?: string;
    /**
     * The time at which the effort was started in the local timezone.
     */
    start_date_local?: string;
    /**
     * The effort\'s distance in meters
     */
    distance?: number;
    /**
     * Whether this effort is the current best on the leaderboard
     */
    is_kom?: boolean;
}

