/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A union type representing the time spent in a given zone.
 */
export interface TimedZoneRange { 
    /**
     * The minimum value in the range.
     */
    min?: number;
    /**
     * The maximum value in the range.
     */
    max?: number;
    /**
     * The number of seconds spent in this zone
     */
    time?: number;
}

