/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SportType } from './sportType.interface';
import { ActivityType } from './activityType.interface';


export interface UpdatableActivity { 
    /**
     * Whether this activity is a commute
     */
    commute?: boolean;
    /**
     * Whether this activity was recorded on a training machine
     */
    trainer?: boolean;
    /**
     * Whether this activity is muted
     */
    hide_from_home?: boolean;
    /**
     * The description of the activity
     */
    description?: string;
    /**
     * The name of the activity
     */
    name?: string;
    type?: ActivityType;
    sport_type?: SportType;
    /**
     * Identifier for the gear associated with the activity. ‘none’ clears gear from activity
     */
    gear_id?: string;
}
export namespace UpdatableActivity {
}


