/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Upload { 
    /**
     * The unique identifier of the upload
     */
    id?: number;
    /**
     * The unique identifier of the upload in string format
     */
    id_str?: string;
    /**
     * The external identifier of the upload
     */
    external_id?: string;
    /**
     * The error associated with this upload
     */
    error?: string;
    /**
     * The status of this upload
     */
    status?: string;
    /**
     * The identifier of the activity this upload resulted into
     */
    activity_id?: number;
}

