/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Waypoint { 
    /**
     * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
     */
    latlng?: number[];
    /**
     * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
     */
    target_latlng?: number[];
    /**
     * Categories that the waypoint belongs to
     */
    categories?: string[];
    /**
     * A title for the waypoint
     */
    title?: string;
    /**
     * A description of the waypoint (optional)
     */
    description?: string;
    /**
     * The number meters along the route that the waypoint is located
     */
    distance_into_route?: number;
}

