/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HeartRateZoneRanges } from './heartRateZoneRanges.interface';
import { PowerZoneRanges } from './powerZoneRanges.interface';


export interface Zones { 
    heart_rate?: HeartRateZoneRanges;
    power?: PowerZoneRanges;
}

