/**
 * Strava API v3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZoneRange { 
    /**
     * The minimum value in the range.
     */
    min?: number;
    /**
     * The maximum value in the range.
     */
    max?: number;
}

